### PR TITLE
Responsive Navbar Added

### PR DESCRIPTION
**Pull request by shiyasmohd**
Issue #1  Fixed
Added a responsive Navbar

### CODE REVIEW

**Comment by ruchika-01p** [comment]
@Shiyasmohd can you send me the screenshots of the header both website and mobile view

**Comment by shiyasmohd** [comment]
> @Shiyasmohd can you send me the screenshots of the header both website and mobile view

**Comment by ruchika-01p** [comment]
@Shiyasmohd Mobile view is fine
In the website view put the logo to extreme left and write Art of Living besides it
and put the other navbar items to extreme right

**Comment by shiyasmohd** [comment]
> @Shiyasmohd Mobile view is fine In the website view put the logo to extreme left and write Art of Living besides it and put the other navbar items to extreme right
Screenshot 2021-10-09 144209

**Comment by ruchika-01p** [comment]
it is fine 
just write text Art of Living to the immediate right of logo then i will accept your pr

**Comment by shiyasmohd** [comment]
> it is fine just write text Art of Living to the immediate right of logo then i will accept your pr
Screenshot 2021-10-09 150051

**Review by ruchika-01p — APPROVED** [review]
PR accepted

**Pull request merged**
